Revert "Force MSVC version"
GitHub Actions runners no longer have this version.

	Found with vswhere: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
	Error: Could not setup Developer Command Prompt: invalid parameters
	[ERROR:vcvars.bat] Toolset directory for version '14.39' was not found.

This reverts commit fc46662998cc433cf9212caa51d7f7dfa1318ccd.